// UK lang variables

tinyMCE.addI18n('en.papaya',{
link_title : 'Insert / edit link',
link_desc : 'Insert / edit link',
link_tab_page : 'Page',
link_tab_url : 'URL',
link_tab_email : 'Email',
link_popup_title : 'Popup',
link_popup_use : 'Open link in popup',
link_popup_width : 'Width',
link_popup_height : 'Height',
link_popup_scrollbars : 'Scrollbars',
link_popup_resize : 'Resizeable',
link_popup_toolbar : 'Toolbar',
link_pageid_title : 'Page id',
link_pagetext_title : 'Text',
link_pagetitle_title : 'Title',
link_url_title : 'URL',
link_urltext_title : 'Link text',
link_urltitle_title : 'Link title',
link_email_title : 'Email address',
link_emailtext_title : 'Link text',
link_emailtitle_title : 'Link title',
link_emailsubject_title : 'Email subject',
link_css_class : 'CSS class',
link_textmode_title : 'Text mode',
link_textmode_auto : 'Page title if available',
link_textmode_yes : 'Text only',
link_textmode_no : 'Page title only',
link_target_title : 'Target',
link_target_self : 'Current window',
link_target_blank : 'New window',

media_title : 'Insert / edit image',
media_desc : 'Insert / edit image',
media_tab_file : 'File',
media_tab_link : 'Link',
media_align : 'Alignment',
media_align_inline : 'Inline',
media_align_left : 'Left',
media_align_center : 'Center',
media_align_right : 'Right',
media_margins : 'Margins',
media_margin_left : 'Left',
media_margin_right : 'Right',
media_margin_top : 'Top',
media_margin_bottom : 'Bottom',
media_size : 'Size',
media_size_width : 'Width',
media_size_height : 'Height',
media_resize_proportional : 'Resize proportional',
media_resize_abs : 'Absolute',
media_resize_max : 'Maximum',
media_resize_min : 'Minimum',
media_resize_mincrop : 'Minimum cropped',
media_get_original_size : 'Get original size',
media_texts : 'Texts',
media_text_subtitle : 'Subtitle',
media_text_alttext : 'Alternative text',
media_link_type : 'Link type',
media_link_type_none : 'None',
media_link_type_popup : 'Popup with original Image',
media_link_type_pageid : 'Page Id',
media_link_type_url : 'URL',
media_link_type_email : 'Email',
media_link_type_file : 'File',
media_link_type_image : 'Image',
media_link_params : 'Parameters',

file_title : 'Insert / edit embedded file',
file_desc : 'Insert / edit embedded file',
file_text_title : 'Title',
file_text_quickinfo : 'Quickinfo',
file_download : 'Force download',
file_download_yes : 'Yes',
file_download_yes : 'No',
file_target : 'Target',
file_target_self : 'Current window',
file_target_blank : 'New window',
file_data : 'File data',
file_data_id : 'Id',
file_data_title : 'Title',
file_data_name : 'Name',
file_data_size : 'Size',
file_select : 'Select file',

image_title : 'Insert / edit dynamic image',
image_desc : 'Insert / edit dynamic image',
image_select : 'Select image',
image_attributes : 'Attributes',
image_preview : 'Preview',

addon_title : 'Insert / edit papaya addon tag',
addon_desc : 'Insert / edit papaya addon tag',
addon_select : 'Select addon',

error_missing : 'Field "%s" needs a value',
error_not_numeric : 'Field "%s" is not numeric. Invalid character at position "%d".',
error_not_alphabetic : 'Field "%s" is not alphabetic. Invalid character at position "%d".',
error_not_alphanumeric : 'Field "%s" is not alphanumeric. Invalid character at position "%d".',
error_not_alnumhyphen : 'Field "%s" allows only A-Z, a-z, 0-9, _ and -. Invalid character at position "%d".',
error_to_large : 'Field "%s" is too large. Must be less then "%d".',
error_to_long : 'Field "%s" is too long. Maximum is "%d" chars.',
error_to_small : 'Field "%s" is too small. Must be greater then "%d".',
error_to_short : 'Field "%s" is too short. Minimum is "%d" chars.',
error_regex_nomatch : 'Field "%s" contains invalid input.',
error_regex_match : 'Field "%s" contains invalid input at character position "%d".',
error_no_select : 'Please select an option for field "%s".',
error_not_checked : 'Please check field "%s".',
error_no_email : 'Field "%s" doesn\'t contain a valid email adress.',
error_no_http : 'Field "%s" doesn\'t contain a valid http adress.',

fieldinfo_pageid : 'Please provide a valid page id.',
fieldinfo_addonguid : 'Please select an addon or cancel this dialog.'

});
